version: "3.8"

services:
  devenv:
    tty: true
    container_name: devenv
    build:
      context: ./devenv
      dockerfile: Dockerfile
      args:
        buildno: 1
    volumes:
      - ./:/app

  postgres:
    image: postgres:12.3
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - "pg_data:/var/lib/postgresql/data"

  adminer:
    image: adminer:4.7.7
    restart: always
    ports:
      - 8080:8080

volumes:
  pg_data:
    driver: local
